os:
- linux

language: php

env:
  global:
    secure: v4ay9b86o/wwBaW+7k7HdB8M7drF274LEkh2SYmKz/vLauc5gbKsEeaoDTek9xAOfa3V/3FDBYecty/qfhjDeo1gIVmvoE4DEf2XjszwyWUqRJTucqT+C8cKxSkbc0b3C/Xw8KF1oaaJ/HMHr/iVk9Q1TOyjdijnoG/PF1CZeSA=

addons:
  apt:
    packages:
      - ant

before_install:
  - wget https://phar.io/releases/phive.phar
  - wget https://phar.io/releases/phive.phar.asc
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/bin/phive

install:
  - ant setup

script:
  - ant test

php:
  - 7.2
  - 7.3
  - 7.4
  - 7.2snapshot
  - 7.3snapshot
  - 7.4snapshot
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true

notifications:
  email: false
