name: Code quality checks
# This workflow is triggered on pushes to the repository.
on:
  - "push"

jobs:
  qa:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.4.0"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.17.0"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --prefer-dist --optimize-autoloader"

      - name: phive
        uses: './.github/actions/phive-ant'
        with:
          args: 'getphive'

      - name: phive install
        uses: './.github/actions/phive-ant'
        env:
          phive.bin: "/phive.phar"
        with:
          args: -Dphive.bin=./phive.phar install-tools

      - name: php-cs-fixer
        uses: './.github/actions/phive-ant'
        env:
          phive.bin: "/phive.phar"
        with:
          args: -Dphive.bin=./phive.phar php-cs-fixer

