name: Code quality checks
# This workflow is triggered on pushes to the repository.
on:
  - "push"

jobs:
  qa:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.4.0"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.17.0"
        with:
          coverage: "none"
          php-version: "8.0"
          tools: "phive"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --prefer-dist --optimize-autoloader"

      - name: phive install
        run: "ant install-tools"

      - name: php-cs-fixer
        run: "ant php-cs-fixer"

